blockchain:
  BlockDbPath: "./data1/blocks"
  KeyStoragePath: "./data1/keys"
network:
  RPCListenAddress: "127.0.0.1:9005"
  ClientAPIAddress: "127.0.0.1:9005"
  protocol_type: "http://"
  P2PListenAddress: ":9004"
  P2PBootstraps:
    - "127.0.0.1:9001"
  ProtocolVersion: 0
  NetworkID: 0
  server_crt: ""
  server_key: ""




  

